---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blah-deployment
  annotations:
    flux.weave.works/automated: "true"
  labels:
    app: blah
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blah
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blah
    spec:
      containers:
      - name: blah
        image: nginx:1.14-perl
        imagePullPolicy: Always
        ports:
        - containerPort: 80
