apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wishlist
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
      - name: wishlist
        image: gcr.io/sweetwater-test/test-mirror-1:5968f29e82af66eb7b895bff1ff6b678ed4c19a2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: wishlist-service
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wishlist-ingress
spec:
  backend:
    serviceName: wishlist-service
    servicePort: 80